name: Build & Smoke Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Build block_game.zig
        run: zig build

      - name: Smoke test (MacOS)
        if: runner.os == 'MacOS'
        run: |
          ./zig-out/bin/demo &
          PID=$!
          sleep 10
          kill $PID || true

      - name: Smoke test (Windows)
        if: runner.os == 'Windows'
        run: Start-Process .\zig-out\bin\demo.exe -PassThru | Tee-Object -Variable p; Start-Sleep 10; Stop-Process $p.Id -Force
